import type { MonitorDefinition } from '../../render/monitors/layered-monitor.js'
import type { MonitorMenuItem } from '../../render/monitors/menu.js'

const back: MonitorMenuItem = { id: 'back', label: 'VOLVER', back: true }
export const carMenuItems: MonitorMenuItem[] = [
  {
    id: 'paint',
    label: 'COLOR COCHE',
    children: [
      { id: 'silver', label: 'GRIS PLATA', action: { type: 'vehicle.paint', value: '#dadde1' } },
      { id: 'black', label: 'NEGRO', action: { type: 'vehicle.paint', value: '#17191e' } },
      { id: 'red', label: 'ROJO', action: { type: 'vehicle.paint', value: '#b91929' } },
      { id: 'blue', label: 'AZUL', action: { type: 'vehicle.paint', value: '#2157a5' } },
      { id: 'white', label: 'BLANCO', action: { type: 'vehicle.paint', value: '#f0f0ea' } },
      back,
    ],
  },
  {
    id: 'mirrors',
    label: 'ESPEJOS',
    children: [
      { id: 'mirror-up', label: 'SUBIR +1', action: { type: 'vehicle.mirror', value: '1' } },
      { id: 'mirror-down', label: 'BAJAR -1', action: { type: 'vehicle.mirror', value: '-1' } },
      back,
    ],
  },
  {
    id: 'map',
    label: 'MAPA',
    children: [
      { id: 'map-car', label: 'SIGUE COCHE', action: { type: 'vehicle.map', value: 'heading' } },
      { id: 'map-north', label: 'NORTE FIJO', action: { type: 'vehicle.map', value: 'north' } },
      back,
    ],
  },
  {
    id: 'gps',
    label: 'POSICION',
    children: [back],
  },
  {
    id: 'engine',
    label: 'MOTOR',
    children: [
      {
        id: 'engine-normal',
        label: 'NORMAL · D',
        action: { type: 'vehicle.engine', value: 'normal' },
      },
      {
        id: 'engine-beast',
        label: 'BESTIA · S',
        action: { type: 'vehicle.engine', value: 'beast' },
      },
      back,
    ],
  },
  {
    id: 'fov',
    label: 'VISTA FOV',
    children: [
      { id: 'fov-wide', label: 'AMPLIAR +5', action: { type: 'vehicle.fov', value: '5' } },
      { id: 'fov-narrow', label: 'REDUCIR -5', action: { type: 'vehicle.fov', value: '-5' } },
      { id: 'fov-reset', label: 'NORMAL', action: { type: 'vehicle.fov', value: 'reset' } },
      back,
    ],
  },
]
/** Edit the panel, positions and bindings here; no keyboard or game logic in the layout. */
export const carMenuDefinition: MonitorDefinition = {
  width: 600,
  height: 400,
  layers: [
    { id: 'background', kind: 'panel', x: 0, y: 0, width: 600, height: 400, color: '#080d16' },
    { id: 'accent', kind: 'panel', x: 22, y: 80, width: 556, height: 4, color: '#ff3344' },
    {
      id: 'title',
      kind: 'text',
      x: 24,
      y: 18,
      width: 552,
      height: 50,
      columns: 18,
      binding: 'title',
      tracking: 0.58,
    },
    ...[0, 1, 2].map((i) => ({
      id: `row${i}`,
      kind: 'text' as const,
      x: 35,
      y: 90 + i * 82,
      width: 561,
      height: 80,
      columns: 11,
      binding: `row${i}`,
      tracking: 0.58,
    })),
    {
      id: 'selection',
      kind: 'bar',
      x: 12,
      y: 98,
      width: 8,
      height: 65,
      color: '#ff3344',
      binding: 'selection',
    },
    {
      id: 'heading',
      kind: 'text',
      x: 24,
      y: 95,
      width: 552,
      height: 110,
      columns: 3,
      binding: 'heading',
      font: 'sans',
      align: 'center',
    },
    {
      id: 'lon',
      kind: 'text',
      x: 35,
      y: 214,
      width: 530,
      height: 42,
      columns: 18,
      binding: 'lon',
      tracking: 0.58,
    },
    {
      id: 'lat',
      kind: 'text',
      x: 35,
      y: 258,
      width: 530,
      height: 42,
      columns: 18,
      binding: 'lat',
      tracking: 0.58,
    },
    {
      id: 'alt',
      kind: 'text',
      x: 35,
      y: 302,
      width: 530,
      height: 42,
      columns: 18,
      binding: 'alt',
      tracking: 0.58,
    },
    {
      id: 'help',
      kind: 'text',
      x: 24,
      y: 350,
      width: 550,
      height: 24,
      columns: 36,
      binding: 'help',
      color: '#9daac2',
      tracking: 0.58,
    },
  ],
}
