import type { MonitorDefinition } from '../../render/monitors/layered-monitor.js'
/** A3-inspired twin dials, shared with the standalone HTML preview assets. */
export const s3ClusterDefinition: MonitorDefinition = {
  width: 640,
  height: 320,
  layers: [
    {
      id: 'face',
      kind: 'image',
      x: 0,
      y: 0,
      width: 640,
      height: 320,
      url: '/monitors/s3-cluster.svg',
    },
    {
      id: 'rpm-needle',
      kind: 'needle',
      x: 27.6,
      y: 63.6,
      width: 204.8,
      height: 204.8,
      url: '/monitors/red-needle.svg',
      pivot: [102.4, 102.4],
      binding: 'rpm',
      min: 0,
      max: 8000,
      fromDegrees: -140,
      toDegrees: 140,
    },
    {
      id: 'speed-needle',
      kind: 'needle',
      x: 407.6,
      y: 63.6,
      width: 204.8,
      height: 204.8,
      url: '/monitors/red-needle.svg',
      pivot: [102.4, 102.4],
      binding: 'speed',
      min: 0,
      max: 320,
      fromDegrees: -140,
      toDegrees: 140,
    },
    {
      id: 'speed',
      kind: 'text',
      x: 232,
      y: 118,
      width: 176,
      height: 80,
      columns: 3,
      binding: 'speedDisplay',
      font: 'sans',
      align: 'center',
    },
    {
      id: 'gear',
      kind: 'text',
      x: 298,
      y: 221,
      width: 44,
      height: 30,
      columns: 2,
      binding: 'gear',
      color: '#ff3548',
    },
  ],
}
