import { test, expect } from '@playwright/test'

test('cycles chase, cockpit and north-up overhead map with adjustable height', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (e) => errors.push(e.message))
  await page.goto('/?scene=circuit')
  await page.locator('#geography-section > summary').click()
  await page.locator('#imagery').selectOption('offline')
  await page.locator('#apply-location').click()
  await expect(page.locator('canvas')).toHaveAttribute('data-assets', 'loaded', { timeout: 20000 })
  await page.locator('#welcome-close').click()
  await page.locator('#play').click()
  await page.waitForTimeout(700)
  await page.keyboard.press('KeyE')
  await expect(page.locator('#player-mode')).toContainText('AUDI')
  await page.keyboard.press('KeyC')
  await expect(page.locator('canvas')).toHaveAttribute('data-camera-mode', 'cockpit')
  await page.keyboard.press('KeyC')
  await expect(page.locator('canvas')).toHaveAttribute('data-camera-mode', 'map')
  await expect(page.locator('canvas')).toHaveAttribute('data-map-height', '350')
  await page.locator('canvas').hover()
  await page.mouse.wheel(0, 300)
  await expect(page.locator('canvas')).not.toHaveAttribute('data-map-height', '350')
  await page.keyboard.down('KeyW')
  await page.waitForTimeout(1800)
  await page.keyboard.up('KeyW')
  await expect(page.locator('#speed')).not.toHaveText('0 km/h')
  await page.screenshot({ path: 'test-results/camera-map.png' })
  await page.keyboard.press('KeyC')
  await expect(page.locator('canvas')).toHaveAttribute('data-camera-mode', 'chase')
  await page.locator('#play').click()
  expect(errors).toEqual([])
})
