import { test, expect } from '@playwright/test'

test('side mirrors capture only while driving in cockpit view', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (e) => errors.push(e.message))
  page.on('console', (e) => {
    if (e.type() === 'error' && /shader|WebGL/i.test(e.text())) errors.push(e.text())
  })
  await page.goto('/?scene=circuit')
  const canvas = page.locator('#viewport > canvas')
  await expect(canvas).toHaveAttribute('data-assets', 'loaded', { timeout: 20000 })
  await page.locator('#welcome-close').click()
  await page.evaluate(() => {
    ;(document.getElementById('sky-time') as HTMLInputElement).value = '2026-06-21T12:00'
    document.getElementById('sky-apply')!.click()
  })
  await expect(canvas).toHaveAttribute('data-assets', 'loaded', { timeout: 20000 })
  await page.locator('#play').click()
  await page.waitForTimeout(700)
  await page.keyboard.press('KeyE')
  await expect(page.locator('#player-mode')).toHaveText('AUDI A3 CABRIO')
  await expect(canvas).toHaveAttribute('data-mirror-active', 'false')
  await page.keyboard.press('Comma')
  await page.keyboard.down('Space')
  await page.waitForTimeout(550)
  await page.screenshot({ path: 'test-results/a3-brakes.png' })
  await page.keyboard.up('Space')
  await page.keyboard.press('Comma')
  await page.keyboard.press('KeyC')
  await expect(canvas).toHaveAttribute('data-mirror-active', 'true')
  await canvas.click({ position: { x: 400, y: 300 } })
  await page.mouse.move(700, 450)
  await page.mouse.move(370, 450, { steps: 10 })
  await expect
    .poll(async () => Number(await canvas.getAttribute('data-mirror-frames')))
    .toBeGreaterThan(0)
  await page.screenshot({ path: 'test-results/a3-mirror.png' })
  await page.keyboard.press('KeyC')
  await expect(canvas).toHaveAttribute('data-camera-mode', 'map')
  await expect(canvas).toHaveAttribute('data-mirror-active', 'false')
  const frames = await canvas.getAttribute('data-mirror-frames')
  await page.waitForTimeout(500)
  expect(await canvas.getAttribute('data-mirror-frames')).toBe(frames)
  await page.keyboard.press('KeyE')
  await expect(canvas).toHaveAttribute('data-mirror-active', 'false')
  await page.waitForTimeout(300)
  expect(await canvas.getAttribute('data-mirror-frames')).toBe(frames)
  expect(errors).toEqual([])
})
