import { test, expect } from '@playwright/test'

test('anchors a drawable CSS screen inside the carrier and changes perspective with the camera', async ({
  page,
}) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/?scene=circuit')
  await page.locator('#welcome-close').click()
  await expect(page.locator('canvas')).toHaveAttribute('data-assets', 'loaded')
  await page.locator('#options-menu-button').click()
  await page.locator('#css-screen-demo').click()
  const panel = page.locator('.carrier-css-screen')
  await expect(panel).toHaveCount(1)
  await page.waitForTimeout(500)
  const bounds = await panel.boundingBox()
  expect(bounds).not.toBeNull()
  await page.mouse.click(bounds!.x + bounds!.width * 0.65, bounds!.y + bounds!.height * 0.5)
  await expect(panel.locator('.css-ink')).toHaveCount(1)
  const before = await panel.evaluate((element) => element.parentElement!.style.transform)
  await page.mouse.move(1100, 780)
  await page.mouse.down({ button: 'right' })
  await page.mouse.move(1070, 770, { steps: 10 })
  await page.mouse.up({ button: 'right' })
  await page.waitForTimeout(500)
  expect(await panel.evaluate((element) => element.parentElement!.style.transform)).not.toBe(before)
  await page.locator('#options-menu-button').click()
  await page.locator('#css-screen-demo').click()
  await page.waitForTimeout(500)
  const next = await panel.boundingBox()
  await page.keyboard.down('Shift')
  await page.mouse.click(next!.x + next!.width * 0.65, next!.y + next!.height * 0.5)
  await page.keyboard.up('Shift')
  await expect(panel.locator('.css-ink')).toHaveCount(0)
  await page.screenshot({ path: 'test-results/carrier-css-screen.png' })
  expect(errors).toEqual([])
})
