import { test, expect } from './studio-test.js'

test('reveals a viewport selection inside a collapsed group and creates from the scene menu', async ({
  page,
}) => {
  await page.goto('/?scene=circuit')
  await expect(page.locator('#viewport > canvas')).toHaveAttribute('data-assets', 'loaded')
  if (await page.locator('#welcome-close').isVisible()) await page.locator('#welcome-close').click()
  const group = page.locator('[data-entity-id="architecture"]')
  const building = page.locator('[data-entity-id="building-0"]')
  await group.click()
  await building.click()
  await page.locator('#focus').click()
  await group.click()
  await expect(building).toHaveCount(0)
  await page.locator('#viewport > canvas').click()
  await expect(building).toHaveAttribute('aria-selected', 'true')
  await expect(group).toHaveAttribute('aria-expanded', 'true')
  await expect(building).toBeInViewport()
  const add = page.getByRole('button', { name: 'Añadir entidad', exact: true })
  await expect(page.locator('#add-box')).toBeHidden()
  await add.click()
  await expect(page.locator('#add-menu')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('#add-menu')).toBeHidden()
  await expect(add).toBeFocused()
  await add.click()
  await page.screenshot({ path: 'test-results/scene-add-menu.png' })
  const before = Number(await page.locator('#entity-count').textContent())
  await page.locator('#add-box').click()
  await expect(page.locator('#entity-count')).toHaveText(String(before + 1))
  await expect(page.locator('#add-menu')).toBeHidden()
  await expect(page.locator('#tree [aria-selected="true"]')).toContainText('Bloque')
  await page.locator('#play').click()
  await expect(page.locator('#play')).toBeEnabled()
  await expect(add).toBeDisabled()
})
