import { expect, it } from 'vitest'
import { HeldKeys } from '../../src/runtime/held-keys.js'

it('expires acceleration and steering when keyup is lost', () => {
  const keys = new HeldKeys()
  keys.press('KeyW', false, 0)
  keys.press('KeyD', false, 100)
  keys.expire(1700)
  expect([...keys.values]).toEqual([])
})
it('keeps a held control refreshed by repeats and releases immediately on keyup', () => {
  const keys = new HeldKeys()
  keys.press('KeyW', false, 0)
  keys.press('KeyW', true, 1000)
  keys.expire(1700)
  expect(keys.values.has('KeyW')).toBe(true)
  keys.release('KeyW')
  expect(keys.values.size).toBe(0)
})
it('ignores queued repeats after focus loss until a fresh press', () => {
  const keys = new HeldKeys()
  keys.press('KeyD', false, 0)
  keys.clear()
  keys.press('KeyD', true, 100)
  expect(keys.values.size).toBe(0)
  keys.press('KeyD', false, 200)
  expect(keys.values.has('KeyD')).toBe(true)
})
it('keeps W+D held when the operating system repeats only D', () => {
  const keys = new HeldKeys()
  keys.press('KeyW', false, 0)
  keys.press('KeyD', false, 100)
  keys.press('KeyD', true, 1400)
  keys.expire(2000)
  expect([...keys.values]).toEqual(['KeyW', 'KeyD'])
})
it('keeps a silently held throttle after steering was tapped and released', () => {
  const keys = new HeldKeys()
  keys.press('KeyW', false, 0)
  for (let t = 500; t <= 1000; t += 33) keys.press('KeyW', true, t)
  // Tapping D moves the OS repeat stream to D; releasing D leaves W held but silent.
  keys.press('KeyD', false, 1100)
  keys.release('KeyD')
  keys.expire(1100 + 5000)
  expect([...keys.values]).toEqual(['KeyW'])
  expect(keys.expirations).toBe(0)
  keys.release('KeyW')
  expect(keys.values.size).toBe(0)
})
it('releases the whole chord when the newest key goes silent without a keyup', () => {
  const keys = new HeldKeys()
  keys.press('KeyW', false, 0)
  keys.press('KeyD', false, 100)
  keys.press('KeyD', true, 600)
  keys.expire(2000)
  expect(keys.values.has('KeyD')).toBe(true)
  keys.expire(2200)
  expect([...keys.values]).toEqual([])
  expect(keys.expirations).toBe(1)
  // A late repeat from the dead stream cannot restart a control.
  keys.press('KeyD', true, 2300)
  expect(keys.values.size).toBe(0)
})
it('keeps non-movement keys and never expires without a repeat stream owner', () => {
  const keys = new HeldKeys()
  keys.press('ShiftLeft', false, 0)
  keys.expire(10000)
  expect(keys.values.has('ShiftLeft')).toBe(true)
  keys.release('ShiftLeft')
  keys.expire(20000)
  expect(keys.expirations).toBe(0)
})
