/** Generate a deterministic implementation reference without evaluating application code. */
import fs from 'node:fs'
import path from 'node:path'
import ts from 'typescript-vue'

const root = process.cwd()
const studio = JSON.parse(fs.readFileSync('package.json', 'utf8')).name === '@nabla/studio'
const roots = studio ? ['studio'] : ['src', 'game']
const destination = 'docs/reference'
const check = process.argv.includes('--check')
const files = []
for (const directory of roots) {
  for (const entry of fs.readdirSync(directory, { recursive: true })) {
    const file = `${directory}/${entry.split(path.sep).join('/')}`
    if (!/\.(ts|vue)$/.test(file) || /\/(test|e2e)\/|\.d\.ts$/.test(file)) continue
    files.push(file)
  }
}
files.sort()
const modules = new Map()
const outputs = new Map()
let functions = 0
const escape = (value) => String(value).replaceAll('|', '\\|').replaceAll('\n', ' ')
function description(node) {
  return (node.jsDoc ?? [])
    .map((doc) => (typeof doc.comment === 'string' ? doc.comment : ''))
    .filter(Boolean)
    .join('\n\n')
}
function symbolName(node, source) {
  if (ts.isConstructorDeclaration(node)) return 'constructor'
  if (node.name) return node.name.getText(source)
  const parent = node.parent
  if (
    ts.isVariableDeclaration(parent) ||
    ts.isPropertyAssignment(parent) ||
    ts.isPropertyDeclaration(parent)
  )
    return parent.name.getText(source)
  return `callback@${source.getLineAndCharacterOfPosition(node.getStart(source)).line + 1}`
}
function callable(node) {
  return (
    ts.isFunctionDeclaration(node) ||
    ts.isFunctionExpression(node) ||
    ts.isArrowFunction(node) ||
    ts.isMethodDeclaration(node) ||
    ts.isConstructorDeclaration(node) ||
    ts.isGetAccessorDeclaration(node) ||
    ts.isSetAccessorDeclaration(node)
  )
}
for (const file of files) {
  const original = fs.readFileSync(file, 'utf8').replaceAll('\r\n', '\n')
  // Preserve line offsets in Vue files so links still address the original SFC.
  let text = original
  if (file.endsWith('.vue')) {
    const ranges = [...original.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)].map((m) => [
      m.index + m[0].indexOf('>') + 1,
      m.index + m[0].lastIndexOf('</script>'),
    ])
    text = original
      .split('')
      .map((c, i) => (c === '\n' || ranges.some(([a, b]) => i >= a && i < b) ? c : ' '))
      .join('')
  }
  const source = ts.createSourceFile(file, text, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS)
  const imports = source.statements
    .filter(ts.isImportDeclaration)
    .map((node) => node.moduleSpecifier.text)
  const exports = source.statements
    .filter(ts.isExportDeclaration)
    .map((node) => node.moduleSpecifier?.text)
    .filter(Boolean)
  const relative = path.posix.relative(path.posix.dirname(`${destination}/${file}.md`), file)
  const header = original
    .match(/^\/\*\*\s*\n?([\s\S]*?)\*\//)?.[1]
    ?.replace(/^\s*\* ?/gm, '')
    .trim()
  const lines = [
    `# ${file}`,
    '',
    '<!-- Generated by scripts/document-code.mjs. Edit source contracts, then regenerate. -->',
    '',
    `[Source](${relative})`,
    '',
  ]
  if (header) lines.push(header, '')
  lines.push(
    '## Module dependencies',
    '',
    ...[...new Set([...imports, ...exports])].map((name) => `- \`${name}\``),
    '',
  )
  let count = 0
  function visit(node, scope = []) {
    let next = scope
    if (ts.isClassDeclaration(node) || ts.isClassExpression(node))
      next = [...scope, node.name?.text ?? 'anonymous class']
    if (callable(node)) {
      const name = symbolName(node, source)
      const qualified = [...scope, name].join('.')
      const line = source.getLineAndCharacterOfPosition(node.getStart(source)).line + 1
      const params = node.parameters.map((p) => p.getText(source).replace(/\s+/g, ' '))
      const result =
        node.type?.getText(source) ??
        (ts.isConstructorDeclaration(node)
          ? 'instance'
          : 'inferred by TypeScript; see implementation')
      const notes = description(node) || description(node.parent)
      lines.push(`## ${qualified}`, '', `[Implementation, line ${line}](${relative}#L${line})`, '')
      if (notes) lines.push(notes, '')
      lines.push('```ts', `${name}(${params.join(', ')}): ${result}`, '```', '')
      const calls = new Set(),
        thrown = new Set()
      // Nested callbacks have their own entries; do not attribute their effects to the parent.
      function details(child) {
        if (child !== node && callable(child)) return
        if (ts.isCallExpression(child) || ts.isNewExpression(child)) {
          const expression = child.expression.getText(source)
          if (expression.length <= 100 && !expression.includes('\n')) calls.add(expression)
        }
        if (ts.isThrowStatement(child))
          thrown.add(child.expression?.getText(source).replace(/\s+/g, ' '))
        ts.forEachChild(child, details)
      }
      details(node)
      if (calls.size)
        lines.push(
          'Direct call sites (syntactic references, not a purity or execution-order guarantee):',
          '',
          ...[...calls].sort().map((call) => `- \`${call.replaceAll('`', '\\`')}\``),
          '',
        )
      if (thrown.size)
        lines.push(
          'Explicit throws in this body:',
          '',
          ...[...thrown].map((value) => `- \`${value.replaceAll('`', '\\`')}\``),
          '',
        )
      count++
      next = [...scope, name]
    }
    ts.forEachChild(node, (child) => visit(child, next))
  }
  visit(source)
  if (!count)
    lines.push(
      'This module contains declarations, data or re-exports; it defines no executable functions.',
      '',
    )
  functions += count
  modules.set(file, count)
  outputs.set(`${destination}/${file}.md`, lines.join('\n'))
}
outputs.set(
  `${destination}/README.md`,
  [
    '# Code reference',
    '',
    'Generated from active production TypeScript and Vue script blocks. Tests, historical journeys, generated declarations and vendor archives are excluded.',
    '',
    'Every module and executable function is indexed, including private helpers, accessors, constructors and anonymous callbacks. Signatures preserve authored types; inferred return types are explicitly identified. Source JSDoc supplies behavioral contracts. Call sites and explicit throws are static observations, not guarantees of purity, complete transitive errors or runtime execution order.',
    '',
    'Regenerate with `node scripts/document-code.mjs`; verify with `node scripts/document-code.mjs --check`. Edit behavioral notes in source rather than generated pages. Source paths and line links are relative, so no workstation paths are embedded.',
    '',
    `Coverage: **${modules.size} modules; ${functions} executable function definitions**.`,
    '',
    '| Module | Functions |',
    '| --- | ---: |',
    ...[...modules].map(([file, count]) => `| [${escape(file)}](${file}.md) | ${count} |`),
    '',
  ].join('\n'),
)
const differences = []
for (const [file, value] of outputs) {
  if (check) {
    if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8').replaceAll('\r\n', '\n') !== value)
      differences.push(file)
  } else {
    fs.mkdirSync(path.dirname(path.join(root, file)), { recursive: true })
    fs.writeFileSync(file, value)
  }
}
// Removed source modules must not leave apparently current reference pages behind.
if (fs.existsSync(destination)) {
  for (const entry of fs.readdirSync(destination, { recursive: true })) {
    const file = `${destination}/${entry.split(path.sep).join('/')}`
    if (!file.endsWith('.md') || outputs.has(file)) continue
    if (!fs.readFileSync(file, 'utf8').includes('<!-- Generated by scripts/document-code.mjs.'))
      continue
    if (check) differences.push(file)
    else fs.unlinkSync(file)
  }
}
if (differences.length) throw new Error(`Outdated code reference: ${differences.join(', ')}`)
console.log(
  `${studio ? 'Studio' : 'Engine'} reference: ${modules.size} modules, ${functions} functions (${check ? 'verified' : 'generated'})`,
)
