import { test, expect } from './studio-test.js'
import { nativeMap } from './native-map.js'
test('travels between native cities and restores authored edits after returning and reloading', async ({
  page,
}) => {
  await nativeMap(page)
  await page.goto('/')
  await page.locator('#travel-menu-button').click()
  await page.locator('#travel-city').selectOption('40.4168,-3.7038')
  await page.locator('#travel-go').click()
  await expect(page.locator('#scene-name')).toHaveText('Madrid · Sol')
  await expect(page.locator('#travel-go')).toBeEnabled()
  await page.locator('#name').fill('Madrid custom car')
  await page.locator('#name').press('Tab')
  await page.locator('#travel-menu-button').click()
  await page.locator('#travel-city').selectOption('43.32969,-1.819606')
  await page.locator('#travel-go').click()
  await expect(page.locator('#scene-name')).toContainText('Irún')
  await expect(page.locator('#travel-go')).toBeEnabled()
  await page.locator('#travel-menu-button').click()
  await page.locator('#travel-city').selectOption('40.4168,-3.7038')
  await page.locator('#travel-go').click()
  await expect(page.locator('#name')).toHaveValue('Madrid custom car')
  await page.locator('#file-menu-button').click()
  await page.locator('#save').click()
  await expect(page.locator('#status')).toHaveText('Guardado local')
  await page.reload()
  await expect(page.locator('#name')).toHaveValue('Madrid custom car')
  await expect(page.locator('[data-entity-id="world-terrain"]')).toHaveCount(0)
})
test('validates coordinates and opens an uncached destination without blocking on providers', async ({
  page,
}) => {
  await page.route('**/prepare/tiles', (r) => r.fulfill({ status: 503, body: 'offline' }))
  await page.route('**/ImageServer/tile/**', (r) => r.fulfill({ status: 503, body: 'offline' }))
  await page.goto('/?scene=circuit')
  const before = await page.locator('#scene-name').textContent()
  await page.locator('#travel-menu-button').click()
  await page.locator('#travel-latitude').fill('91')
  await page.locator('#travel-go').click()
  await expect(page.locator('#scene-name')).toHaveText(before!)
  await page.locator('#travel-latitude').fill('52.5163')
  await page.locator('#travel-longitude').fill('13.3777')
  await page.locator('#travel-go').click()
  await expect(page.locator('#viewport > canvas')).toHaveAttribute('data-world', 'destination')
  await expect(page.locator('#world-loading')).toBeHidden()
  await expect(page.locator('#latitude')).toHaveValue('52.5163')
  await expect(page.locator('#play')).toBeEnabled()
})
